service: serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  timeout: 30

  environment:
    AccountID: ${env:AccountID}
    BudgetName: ${env:BudgetName}
    WebhookURL: ${env:WebhookURL}

functions:
  billing:
    handler: bin/bootstrap
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    useDocker: true
